import type { Metadata } from "next";
import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";
import ErrorWrapper from "./components/share/ErrorWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "My first Next JS ",
    template: "%s | next js",
  },
  description: "Generated by create next app",
};

// global layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} ${geistSans.variable} `}>
        <p className="text-red-600 text-xs float-end">Global layout</p>
        {/* <ErrorWrapper> */}
        <main className="lg:px-10">{children}</main>
        {/* </ErrorWrapper> */}
      </body>
    </html>
  );
}
