import type { Metadata } from "next";
import Navbar from "../components/share/Navbar";
import "../globals.css";

import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "My first Next JS ",
    template: "%s | next js",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} ${geistSans.variable} `}>
        <section className="lg:px-10">
          <Navbar />
          {children}
        </section>
      </body>
    </html>
  );
}
